#####################################################################
# This is Jekyll's configuration file for this project.
#
# For more information, see the documentation:
#
#     https://jekyllrb.com/docs/configuration/
#####################################################################

# Site settings.
# Set a title and description in other languages using the `site_title`
# and `site_description` keys in the appropriate `_data/strings/` data
# file for the desired language.
title: Example Site
description: >-
    Site description.
timezone: America/New_York # Use the TZ database: https://en.wikipedia.org/wiki/TZID
type: Thing                # Use a sensible value from Schema.org.

# Jekyll SEO Tag metadata.
# See https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
author: exampleauthor
lang: &lang >- # Default language, YAML anchor is used elsewhere.
    en_US
logo: /static/images/main-logo.png
facebook:
    publisher: FacebookPageID
social:
    links:
        - https://www.facebook.com/FacebookPageID
        - https://www.instagram.com/InstagramHandle

# Blog settings.
paginate: 5    # How many posts per HTML page.
paginate_path: "/blog/page/:num/"
date_format: "%B %e, %Y"
time_format: "%l:%M %p"

# Collections metadata.
collections:
    events:
        output: true
        permalink: /:collection/:title
        sort_by: startDate

# Front matter defaults.
# See https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:

  # Set the default page variables.
  - scope:
      path: "" # An empty string here means all files in the project.
    values:
      layout: html5
      lang: *lang

  # Set the correct layout for collection types.
  - scope:
      type: events
    values:
      layout: event
  - scope:
      type: posts
    values:
      layout: post

  # Set the `lang` page variable for language-specific subdirectories.
  - scope:
      path: es
    values:
      lang: es

# iCalendar settings.
iCalendar:
    defaults:
        location: 123 Some Place
        status: CONFIRMED
        image: /static/images/event-placeholder-image.jpg

# Build settings.
markdown: kramdown
include:
    - .nojekyll
exclude:
    - .gitmodules
    - .gitignore
    - .github
    - Gemfile
    - Gemfile.lock
    - README.md
    - vendor

    # Exclude unnecessary files from the flag-icon-css library.
    # See this repository's `.gitmodules` file.
    - static/flag-icon-css/*.coffee
    - static/flag-icon-css/*.html
    - static/flag-icon-css/*.json
    - static/flag-icon-css/*.lock
    - static/flag-icon-css/*.md
    - static/flag-icon-css/*.sh
    - static/flag-icon-css/*.yaml
    - static/flag-icon-css/assets

# Load whitelisted plugins.
# See https://help.github.com/en/articles/configuring-jekyll-plugins
plugins:
    # GitHub Pages-compatible plugins.
    - jekyll-seo-tag
    - jekyll-feed

    # Forestry integration plugins.
    - jekyll-menus
